<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>MRC.Gui</AssemblyName>
    <RootNamespace>MRC.Gui</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MRC.Core\MRC.Core.csproj" />
  </ItemGroup>
</Project>
